# configs/spark/spark-defaults.conf
spark.master                     spark://spark-master:7077
spark.sql.adaptive.enabled       true
spark.sql.adaptive.coalescePartitions.enabled true
spark.sql.hive.metastore.version 3.1.3
spark.sql.hive.metastore.jars    builtin
spark.sql.catalogImplementation  hive
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.sql.warehouse.dir          hdfs://namenode:9000/user/hive/warehouse
spark.hadoop.hive.metastore.uris thrift://hive-metastore:9083
spark.hadoop.bronze.path         hdfs://namenode:9000/data/bronze
spark.hadoop.silver.path         hdfs://namenode:9000/data/silver
spark.hadoop.gold.path           hdfs://namenode:9000/data/gold
